<link rel="stylesheet" href="{{ asset('assets-front/css/bootstrap.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets-front/css/owl.carousel.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets-front/css/flaticon.css') }}">
<link rel="stylesheet" href="{{ asset('assets-front/css/slicknav.css') }}">
<link rel="stylesheet" href="{{ asset('assets-front/css/animate.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets-front/css/magnific-popup.css') }}">
<link rel="stylesheet" href="{{ asset('assets-front/css/fontawesome-all.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets-front/css/themify-icons.css') }}">
<link rel="stylesheet" href="{{ asset('assets-front/css/slick.css') }}">
<link rel="stylesheet" href="{{ asset('assets-front/css/nice-select.css') }}">
<link rel="stylesheet" href="{{ asset('assets-front/css/style.css') }}">